theme: jekyll-theme-minimal
title: umati showcase specification
description: This provides the specification to connect to the umati showcase
logo: img/umati_logo.svg
show_downloads: false
plugins:
  - jemoji
  - jekyll-titles-from-headings
