# SPDX-License-Identifier: MIT
# generated by datamodel-codegen:
#   filename:  metadata_opcua_umati_v3_json_metadata_vdw_server-cpp-dev_ShowcaseMachineTool_Identification.json
#   timestamp: 2026-07-28T08:17:34+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DataType(BaseModel):
    Id: int


class Description(BaseModel):
    Text: str


class Key(BaseModel):
    Name: str


class TypeId(BaseModel):
    Id: int


class ReferenceTypeId(BaseModel):
    Id: int


class NodeId(BaseModel):
    Id: int
    Namespace: int


class BrowseName(BaseModel):
    Name: str
    Uri: int


class DisplayName(BaseModel):
    Text: str


class TypeDefinition(BaseModel):
    Id: int
    Namespace: int | None = None


class Body1(BaseModel):
    ReferenceTypeId_1: ReferenceTypeId = Field(..., alias='ReferenceTypeId')
    IsForward: bool
    NodeId_1: NodeId = Field(..., alias='NodeId')
    BrowseName_1: BrowseName = Field(..., alias='BrowseName')
    DisplayName_1: DisplayName = Field(..., alias='DisplayName')
    NodeClass: int
    TypeDefinition_1: TypeDefinition | None = Field(None, alias='TypeDefinition')


class Body(BaseModel):
    TypeId_1: TypeId = Field(..., alias='TypeId')
    Body: Body1


class BodyItem(BaseModel):
    Type: int
    Body_1: Body = Field(..., alias='Body')


class Value(BaseModel):
    Type: int
    Body: list[BodyItem]


class Property(BaseModel):
    Key_1: Key = Field(..., alias='Key')
    Value_1: Value = Field(..., alias='Value')


class Field1(BaseModel):
    Name: str
    FieldFlags: int
    BuiltInType: int
    DataType_1: DataType = Field(..., alias='DataType')
    ValueRank: int
    MaxStringLength: int
    DataSetFieldId: str
    Description_1: Description | None = Field(None, alias='Description')
    Properties: list[Property] | None = None


class ConfigurationVersion(BaseModel):
    MajorVersion: int
    MinorVersion: int


class MetaData(BaseModel):
    Namespaces: list[str]
    Name: str
    Fields: list[Field1]
    ConfigurationVersion_1: ConfigurationVersion = Field(
        ..., alias='ConfigurationVersion'
    )


class Payload(BaseModel):
    MessageId: str
    MessageType: str
    PublisherId: str
    DataSetWriterId: int
    MetaData_1: MetaData = Field(..., alias='MetaData')


class Model(BaseModel):
    topic: str
    payload: Payload
